const videoState = {
  type: null,
  url: "",
  title: "Chưa có video",
  captions: [],
  activeCueIndex: -1,
  autoFollow: true,
  loopCue: false,
  pauseEachCue: false,
  pausedAtCue: -1,
  manualCueLockIndex: -1,
  manualCueLockUntil: 0,
  ready: false,
  youtubePlayer: null,
  youtubeApiPromise: null,
  pendingYouTubeId: "",
  pendingYouTubeUrl: "",
  embedBlocked: false,
  embedAllowed: null,
  localVideoObjectUrl: "",
  pollingTimer: null,
  lastRenderedActive: -2,
  sourceLabel: "",
  lastCaptionError: "",
  maxWatched: 0,
  libraryItemId: "",
  lastLibraryPersist: 0
};

const dictationState = {
  itemId: "",
  segments: [],
  index: 0,
  mode: "normal",
  segmentLength: "normal",
  autoNext: true,
  showTranscript: false,
  showAnswer: false,
  hintLevel: 0,
  checked: null,
  progress: {},
  replayTimer: null,
  sourceStatus: "voice",
  loading: false,
  segmentSignature: "",
  mediaUrl: "",
  playbackRate: 1,
  playbackGuard: null,
  loopSegment: false,
  loopTimer: null,
  pendingReplay: false,
  youtubePlayer: null,
  youtubePlayerReady: false,
  youtubeVideoId: ""
};

const state = {
  currentUser: null,
  cards: [],
  xp: Number(appStorage.getItem("wordinary_xp") || appStorage.getItem("lingoleaf_xp") || 120),
  streak: Number(appStorage.getItem("wordinary_streak") || appStorage.getItem("lingoleaf_streak") || 3),
  daily: Number(appStorage.getItem("wordinary_daily") || appStorage.getItem("lingoleaf_daily") || 0),
  dailyGoal: Number(appStorage.getItem("wordinary_daily_goal") || 8),
  dailyXp: Number(appStorage.getItem("wordinary_daily_xp") || 0),
  longestStreak: Number(appStorage.getItem("wordinary_longest_streak") || 0),
  theme: appStorage.getItem("wordinary_theme") || appStorage.getItem("lingoleaf_theme") || "light",
  article: SAMPLE_ARTICLE,
  articles: [],
  libraryArticleId: null,
  libraryWord: "",
  libraryMatchIndex: 0,
  readerHighlightedWords: (() => {
    try {
      const words = JSON.parse(appStorage.getItem("wordinary_reader_highlight_words") || "[]");
      return Array.isArray(words) ? words : [];
    } catch (_) {
      return [];
    }
  })(),
  suppressProgress: false,
  sessionSaved: 0,
  sessionXp: 0,
  selection: null,
  currentTab: "pastePanel",
  uploadedFile: null,
  libraryItems: [],
  libraryFilter: "all",
  currentLibraryItemId: null,
  pendingPdfLibraryId: null,
  reviewQueue: [],
  reviewOriginalDeck: [],
  reviewMissedQueue: [],
  reviewIndex: 0,
  reviewFlipped: false,
  reviewMode: "due",
  reviewRound: 1,
  reviewRoundKnown: 0,
  reviewRoundMissedCount: 0,
  reviewSessionStarted: false,
  reviewSummaryVisible: false,
  reviewSessionId: "",
  reviewLoading: false,
  editingCardId: null,
  editingIcon: null,
  language: appStorage.getItem("wordinary_language") || "en",
  readerRailCollapsed: appStorage.getItem("wordinary_reader_rail") === "collapsed",
  mainSidebarCollapsed: appStorage.getItem("wordinary_main_sidebar") === "collapsed",
  fontSize: Number(appStorage.getItem("wordinary_font") || appStorage.getItem("lingoleaf_font") || 21)
};
